/**
 * AI Service Module — Google Gemini API Integration & Planogram Assistant
 * Integrates Gemini 2.5 Flash / 1.5 Flash for answering natural language questions about the Cheatsheet PDF.
 * Also provides an instant offline fallback if no API key is provided.
 */
(function(window) {
  'use strict';

  class AiService {
    constructor(planogramEngine) {
      this.planogramEngine = planogramEngine;
      this.apiKey = localStorage.getItem('scandock_gemini_api_key') || '';
      this.model = 'gemini-2.5-flash';
      this.chatHistory = [];
    }

    setApiKey(key) {
      this.apiKey = (key || '').trim();
      if (this.apiKey) {
        localStorage.setItem('scandock_gemini_api_key', this.apiKey);
      } else {
        localStorage.removeItem('scandock_gemini_api_key');
      }
    }

    getApiKey() {
      return this.apiKey;
    }

    hasApiKey() {
      return Boolean(this.apiKey);
    }

    /**
     * Ask a question about the Cheatsheet PDF
     * @param {string} userPrompt 
     * @returns {Promise<string>}
     */
    async ask(userPrompt) {
      if (!userPrompt || !userPrompt.trim()) {
        return 'Please enter a valid question or product code.';
      }

      const prompt = userPrompt.trim();

      // Check if user is asking for a specific product code
      const codeMatch = prompt.match(/\b\d{6,14}\b/);
      if (codeMatch) {
        const product = this.planogramEngine.lookup(codeMatch[0]);
        if (product) {
          const localAnswer = `📍 **Found in Planogram:**\n` +
            `- **Code**: \`${product.code}\`\n` +
            `- **Section / Rack**: **${product.section}** (Page ${product.page})\n` +
            `- **Exact Position**: **Position ${product.position}** (${product.slotType})\n` +
            `- **Signage Price**: **₹${product.signage}**\n` +
            `- **Color**: **${product.color}**\n` +
            (product.remarks ? `- **Instructions**: *${product.remarks}*\n` : '') +
            (product.capacity ? `- **Capacity**: ${product.capacity}\n` : '');

          if (!this.hasApiKey()) {
            return localAnswer + `\n\n*(Answered via Local Zero-Latency Engine. Add your Gemini API key in settings for full conversational reasoning).*`;
          }
        }
      }

      // If user has provided Gemini API key, call Gemini endpoint
      if (this.hasApiKey()) {
        try {
          return await this.callGemini(prompt);
        } catch (err) {
          console.error('Gemini API call failed, falling back to local reasoning:', err);
          return this.localFallbackAnswer(prompt, err.message);
        }
      } else {
        return this.localFallbackAnswer(prompt);
      }
    }

    async callGemini(userPrompt) {
      const items = this.planogramEngine.getAllItems();
      const planogramSummary = items.map(it => 
        `Code: ${it.code} | Section: ${it.section} | Pos: ${it.position} | Price: ${it.signage} | Color: ${it.color} | Remark: ${it.remarks || 'None'}`
      ).join('\n');

      const systemInstruction = 
        `You are the expert retail visual merchandising terminal AI for "Scan Dock". ` +
        `Your job is to answer store staff questions about product placements, shelf positions, signage prices, and display guidelines based on this store planogram cheatsheet:\n\n` +
        `PLANOGRAM DATA:\n${planogramSummary}\n\n` +
        `Be concise, accurate, professional, and highlight the exact rack section, position number, and price clearly.`;

      const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${this.model}:generateContent?key=${this.apiKey}`;

      const payload = {
        contents: [
          {
            role: 'user',
            parts: [{ text: `${systemInstruction}\n\nUser Question: ${userPrompt}` }]
          }
        ],
        generationConfig: {
          temperature: 0.2,
          maxOutputTokens: 800
        }
      };

      const response = await fetch(endpoint, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });

      if (!response.ok) {
        const errJson = await response.json().catch(() => ({}));
        const errMsg = errJson.error ? errJson.error.message : response.statusText;
        throw new Error(errMsg || `HTTP Error ${response.status}`);
      }

      const data = await response.json();
      if (data.candidates && data.candidates[0] && data.candidates[0].content) {
        return data.candidates[0].content.parts[0].text;
      }

      return 'No answer generated by AI model.';
    }

    /**
     * High-speed local reasoning when no API key is provided
     */
    localFallbackAnswer(prompt, optionalError = null) {
      const p = prompt.toLowerCase();
      const items = this.planogramEngine.getAllItems();

      // Query: section info (e.g. "M6", "M8", "M9", "M10", "MT2")
      const sectionMatch = p.match(/(m6|m8|m9|m10|mt2)/);
      if (sectionMatch) {
        const secQuery = sectionMatch[0].toUpperCase();
        const matches = items.filter(it => it.section.toUpperCase().includes(secQuery));
        if (matches.length > 0) {
          const sample = matches.slice(0, 5).map(m => `• **Pos ${m.position}**: \`${m.code}\` — ${m.color} (₹${m.signage})`).join('\n');
          return `📦 **Section ${matches[0].section}:**\nFound **${matches.length}** planned positions in this section.\n\n${sample}\n` +
            (matches.length > 5 ? `\n*...and ${matches.length - 5} more items in this rack.*` : '') +
            (optionalError ? `\n\n*(Gemini API Note: ${optionalError})*` : '');
        }
      }

      // Query: price search (e.g. "899", "199", "399")
      const priceMatch = p.match(/\b(199|399|499|799|899|999)\b/);
      if (priceMatch) {
        const price = priceMatch[0];
        const matches = items.filter(it => it.signage === price);
        if (matches.length > 0) {
          const sample = matches.slice(0, 5).map(m => `• **${m.section} / Pos ${m.position}**: \`${m.code}\` (${m.color})`).join('\n');
          return `💰 **Items with Signage ₹${price}:**\nTotal **${matches.length}** items found:\n\n${sample}\n` +
            (matches.length > 5 ? `\n*...and ${matches.length - 5} more items.*` : '');
        }
      }

      return `ℹ️ **Local Cheatsheet Assistant:**\n` +
        `Our database currently contains **${items.length} product placements** across M6, M8, M9, M10, and MT2 racks.\n\n` +
        `- Type any product code (e.g. \`301081626\`) to locate its exact hanger/shelf position.\n` +
        `- Type a section name like \`M6\` or \`M9\` to list its display layout.\n\n` +
        `*(To enable full Google Gemini conversational AI, click the **AI Settings** button at the top to paste your Gemini API key).*`;
    }
  }

  window.AiService = AiService;
})(window);
