/**
 * Preloaded Planogram Cheatsheet Dataset
 * Extracted directly from the Retail Visual Merchandising Cheatsheet Document
 * Sections: M6 DENIM, M8 DENIM MONO, M9 ESSENTIALS, M10 ESSENTIALS, MT2-FRONT, MT2-BACK
 */
window.DEFAULT_PLANOGRAM_DATA = [
  // --- PAGE 1: M6 DENIM ---
  {
    code: "301081626",
    section: "M6 DENIM",
    page: 1,
    signage: "899",
    color: "WHITE",
    position: 1,
    totalPositions: 14,
    slotType: "Hanger (Denim)",
    shelf: "Top Row / Hanger 1",
    newLine: "NO",
    cutSize: "NO",
    capacity: "14 pcs Per option Denim",
    remarks: "LAYER 1ST PIECE OF OPTION 1 WITH OPTION 3."
  },
  {
    code: "301075847",
    section: "M6 DENIM",
    page: 1,
    signage: "899",
    color: "GREY",
    position: 2,
    totalPositions: 14,
    slotType: "Hanger (Denim)",
    shelf: "Top Row / Hanger 2",
    newLine: "NO",
    cutSize: "NO",
    capacity: "14 pcs Per option Denim",
    remarks: "LAYER 1ST PIECE OF OPTION 1 WITH OPTION 3."
  },
  {
    code: "301081624",
    section: "M6 DENIM",
    page: 1,
    signage: "899",
    color: "LT INDIGO",
    position: 3,
    totalPositions: 14,
    slotType: "Hanger (Denim)",
    shelf: "Top Row / Hanger 3",
    newLine: "NO",
    cutSize: "NO",
    capacity: "14 pcs Per option Denim",
    remarks: "LAYER 1ST PIECE OF OPTION 1 WITH OPTION 3."
  },
  {
    code: "301081625",
    section: "M6 DENIM",
    page: 1,
    signage: "899",
    color: "TINT",
    position: 4,
    totalPositions: 14,
    slotType: "Hanger (Denim)",
    shelf: "Top Row / Hanger 4",
    newLine: "NO",
    cutSize: "NO",
    capacity: "14 pcs Per option Denim",
    remarks: "LAYER 1ST PIECE OF OPTION 1 WITH OPTION 3."
  },
  {
    code: "301031222",
    section: "M6 DENIM",
    page: 1,
    signage: "199",
    color: "WHITE",
    position: 5,
    totalPositions: 14,
    slotType: "Shelf Stack (Tees)",
    shelf: "Middle Shelf / Stack 5",
    newLine: "NO",
    cutSize: "NO",
    capacity: "15 pcs Per option Tees",
    remarks: ""
  },
  {
    code: "301081994",
    section: "M6 DENIM",
    page: 1,
    signage: "199",
    color: "BALTIC",
    position: 6,
    totalPositions: 14,
    slotType: "Shelf Stack (Tees)",
    shelf: "Middle Shelf / Stack 6",
    newLine: "NO",
    cutSize: "NO",
    capacity: "15 pcs Per option Tees",
    remarks: ""
  },
  {
    code: "301078439",
    section: "M6 DENIM",
    page: 1,
    signage: "199",
    color: "WARM TAUPE",
    position: 7,
    totalPositions: 14,
    slotType: "Shelf Stack (Tees)",
    shelf: "Middle Shelf / Stack 7",
    newLine: "NO",
    cutSize: "NO",
    capacity: "15 pcs Per option Tees",
    remarks: ""
  },
  {
    code: "301078444",
    section: "M6 DENIM",
    page: 1,
    signage: "199",
    color: "KHAKI",
    position: 8,
    totalPositions: 14,
    slotType: "Shelf Stack (Tees)",
    shelf: "Middle Shelf / Stack 8",
    newLine: "NO",
    cutSize: "NO",
    capacity: "15 pcs Per option Tees",
    remarks: ""
  },
  {
    code: "301031226",
    section: "M6 DENIM",
    page: 1,
    signage: "199",
    color: "BLACK",
    position: 9,
    totalPositions: 14,
    slotType: "Shelf Stack (Tees)",
    shelf: "Middle Shelf / Stack 9",
    newLine: "NO",
    cutSize: "NO",
    capacity: "15 pcs Per option Tees",
    remarks: ""
  },
  {
    code: "301078443",
    section: "M6 DENIM",
    page: 1,
    signage: "199",
    color: "CLOUD DANCER",
    position: 10,
    totalPositions: 14,
    slotType: "Bottom Shelf Stack (Tees)",
    shelf: "Bottom Shelf / Stack 10",
    newLine: "NO",
    cutSize: "NO",
    capacity: "15 pcs Per option Tees",
    remarks: ""
  },
  {
    code: "301078442",
    section: "M6 DENIM",
    page: 1,
    signage: "199",
    color: "CAPPUCCINO",
    position: 11,
    totalPositions: 14,
    slotType: "Bottom Shelf Stack (Tees)",
    shelf: "Bottom Shelf / Stack 11",
    newLine: "NO",
    cutSize: "NO",
    capacity: "15 pcs Per option Tees",
    remarks: ""
  },
  {
    code: "301078446",
    section: "M6 DENIM",
    page: 1,
    signage: "199",
    color: "WINE TASTING",
    position: 12,
    totalPositions: 14,
    slotType: "Bottom Shelf Stack (Tees)",
    shelf: "Bottom Shelf / Stack 12",
    newLine: "NO",
    cutSize: "NO",
    capacity: "15 pcs Per option Tees",
    remarks: ""
  },
  {
    code: "301078441",
    section: "M6 DENIM",
    page: 1,
    signage: "199",
    color: "TEAL",
    position: 13,
    totalPositions: 14,
    slotType: "Bottom Shelf Stack (Tees)",
    shelf: "Bottom Shelf / Stack 13",
    newLine: "NO",
    cutSize: "NO",
    capacity: "15 pcs Per option Tees",
    remarks: ""
  },
  {
    code: "301078440",
    section: "M6 DENIM",
    page: 1,
    signage: "199",
    color: "FOREST NIGHT",
    position: 14,
    totalPositions: 14,
    slotType: "Bottom Shelf Stack (Tees)",
    shelf: "Bottom Shelf / Stack 14",
    newLine: "NO",
    cutSize: "NO",
    capacity: "15 pcs Per option Tees",
    remarks: ""
  },

  // --- PAGE 2: M8 DENIM MONO ---
  {
    code: "301081946",
    section: "M8 DENIM MONO",
    page: 2,
    signage: "899",
    color: "LT INDIGO",
    position: 23,
    totalPositions: 14,
    slotType: "Hanger",
    shelf: "Top Row / Hanger 23",
    newLine: "YES",
    cutSize: "NO",
    capacity: "14 pcs Per option Denim",
    remarks: ""
  },
  {
    code: "301081947",
    section: "M8 DENIM MONO",
    page: 2,
    signage: "899",
    color: "GREY",
    position: 24,
    totalPositions: 14,
    slotType: "Hanger",
    shelf: "Top Row / Hanger 24",
    newLine: "YES",
    cutSize: "NO",
    capacity: "14 pcs Per option Denim",
    remarks: ""
  },
  {
    code: "301075849",
    section: "M8 DENIM MONO",
    page: 2,
    signage: "899",
    color: "MD INDIGO",
    position: 25,
    totalPositions: 14,
    slotType: "Hanger",
    shelf: "Top Row / Hanger 25",
    newLine: "NO",
    cutSize: "NO",
    capacity: "14 pcs Per option Denim",
    remarks: ""
  },
  {
    code: "301081948",
    section: "M8 DENIM MONO",
    page: 2,
    signage: "899",
    color: "BLACK",
    position: 26,
    totalPositions: 14,
    slotType: "Hanger",
    shelf: "Top Row / Hanger 26",
    newLine: "YES",
    cutSize: "NO",
    capacity: "14 pcs Per option Denim",
    remarks: ""
  },
  {
    code: "301079821",
    section: "M8 DENIM MONO",
    page: 2,
    signage: "199",
    color: "CLOUD DANCER",
    position: 27,
    totalPositions: 14,
    slotType: "Shelf Stack",
    shelf: "Middle Shelf / Stack 27",
    newLine: "NO",
    cutSize: "NO",
    capacity: "15 pcs Per option Tees",
    remarks: ""
  },
  {
    code: "301079822",
    section: "M8 DENIM MONO",
    page: 2,
    signage: "199",
    color: "COASTAL SHADE",
    position: 28,
    totalPositions: 14,
    slotType: "Shelf Stack",
    shelf: "Middle Shelf / Stack 28",
    newLine: "NO",
    cutSize: "NO",
    capacity: "15 pcs Per option Tees",
    remarks: ""
  },
  {
    code: "301081656",
    section: "M8 DENIM MONO",
    page: 2,
    signage: "199",
    color: "SHIFTING SAND",
    position: 29,
    totalPositions: 14,
    slotType: "Shelf Stack",
    shelf: "Middle Shelf / Stack 29",
    newLine: "YES",
    cutSize: "NO",
    capacity: "15 pcs Per option Tees",
    remarks: ""
  },
  {
    code: "301081658",
    section: "M8 DENIM MONO",
    page: 2,
    signage: "199",
    color: "APPLE GREEN",
    position: 30,
    totalPositions: 14,
    slotType: "Shelf Stack",
    shelf: "Middle Shelf / Stack 30",
    newLine: "YES",
    cutSize: "NO",
    capacity: "15 pcs Per option Tees",
    remarks: ""
  },
  {
    code: "301081654",
    section: "M8 DENIM MONO",
    page: 2,
    signage: "199",
    color: "BLACK",
    position: 31,
    totalPositions: 14,
    slotType: "Shelf Stack",
    shelf: "Middle Shelf / Stack 31",
    newLine: "YES",
    cutSize: "NO",
    capacity: "15 pcs Per option Tees",
    remarks: ""
  },
  {
    code: "301081655",
    section: "M8 DENIM MONO",
    page: 2,
    signage: "199",
    color: "WHITE",
    position: 32,
    totalPositions: 14,
    slotType: "Bottom Shelf Stack",
    shelf: "Bottom Shelf / Stack 32",
    newLine: "YES",
    cutSize: "NO",
    capacity: "15 pcs Per option Tees",
    remarks: ""
  },
  {
    code: "301079824",
    section: "M8 DENIM MONO",
    page: 2,
    signage: "199",
    color: "DARK CITRON",
    position: 33,
    totalPositions: 14,
    slotType: "Bottom Shelf Stack",
    shelf: "Bottom Shelf / Stack 33",
    newLine: "NO",
    cutSize: "NO",
    capacity: "15 pcs Per option Tees",
    remarks: ""
  },
  {
    code: "301079819",
    section: "M8 DENIM MONO",
    page: 2,
    signage: "199",
    color: "KARANA RED",
    position: 34,
    totalPositions: 14,
    slotType: "Bottom Shelf Stack",
    shelf: "Bottom Shelf / Stack 34",
    newLine: "NO",
    cutSize: "NO",
    capacity: "15 pcs Per option Tees",
    remarks: ""
  },
  {
    code: "301081657",
    section: "M8 DENIM MONO",
    page: 2,
    signage: "199",
    color: "BOTTLE GREEN",
    position: 35,
    totalPositions: 14,
    slotType: "Bottom Shelf Stack",
    shelf: "Bottom Shelf / Stack 35",
    newLine: "YES",
    cutSize: "NO",
    capacity: "15 pcs Per option Tees",
    remarks: ""
  },
  {
    code: "301079823",
    section: "M8 DENIM MONO",
    page: 2,
    signage: "199",
    color: "BLACK",
    position: 36,
    totalPositions: 14,
    slotType: "Bottom Shelf Stack",
    shelf: "Bottom Shelf / Stack 36",
    newLine: "NO",
    cutSize: "NO",
    capacity: "15 pcs Per option Tees",
    remarks: ""
  },

  // --- PAGE 3: M9 ESSENTIALS ---
  {
    code: "301080548",
    section: "M9 ESSENTIALS",
    page: 3,
    signage: "399",
    color: "GROUND COFFEE",
    position: 1,
    totalPositions: 12,
    slotType: "Shacket Hanger",
    shelf: "Top Shacket Row 1",
    newLine: "NO",
    cutSize: "NO",
    capacity: "Hang 14 pcs, Fold 9 pcs",
    remarks: "LAYER OPTIONS: 1&2, 3&4."
  },
  {
    code: "301079214",
    section: "M9 ESSENTIALS",
    page: 3,
    signage: "999",
    color: "WHITE",
    position: 2,
    totalPositions: 12,
    slotType: "Shacket Hanger",
    shelf: "Top Shacket Row 2",
    newLine: "NO",
    cutSize: "NO",
    capacity: "Hang 14 pcs, Fold 9 pcs",
    remarks: "LAYER OPTIONS: 1&2, 3&4."
  },
  {
    code: "301080551",
    section: "M9 ESSENTIALS",
    page: 3,
    signage: "399",
    color: "WHITE",
    position: 3,
    totalPositions: 12,
    slotType: "Shacket Hanger",
    shelf: "Top Shacket Row 3",
    newLine: "NO",
    cutSize: "NO",
    capacity: "Hang 14 pcs, Fold 9 pcs",
    remarks: "LAYER OPTIONS: 1&2, 3&4."
  },
  {
    code: "301079213",
    section: "M9 ESSENTIALS",
    page: 3,
    signage: "999",
    color: "DARK NAVY",
    position: 4,
    totalPositions: 12,
    slotType: "Shacket Hanger",
    shelf: "Top Shacket Row 4",
    newLine: "NO",
    cutSize: "NO",
    capacity: "Hang 14 pcs, Fold 9 pcs",
    remarks: "LAYER OPTIONS: 1&2, 3&4."
  },
  {
    code: "301076554",
    section: "M9 ESSENTIALS",
    page: 3,
    signage: "999",
    color: "OLIVE",
    position: 5,
    totalPositions: 12,
    slotType: "Folded Tee Stack",
    shelf: "Middle Shelf 5",
    newLine: "NO",
    cutSize: "NO",
    capacity: "",
    remarks: ""
  },
  {
    code: "301080549",
    section: "M9 ESSENTIALS",
    page: 3,
    signage: "399",
    color: "LAVENDER",
    position: 6,
    totalPositions: 12,
    slotType: "Folded Tee Stack",
    shelf: "Middle Shelf 6",
    newLine: "NO",
    cutSize: "NO",
    capacity: "",
    remarks: ""
  },
  {
    code: "301076556",
    section: "M9 ESSENTIALS",
    page: 3,
    signage: "999",
    color: "BLACK",
    position: 7,
    totalPositions: 12,
    slotType: "Folded Tee Stack",
    shelf: "Middle Shelf 7",
    newLine: "NO",
    cutSize: "NO",
    capacity: "",
    remarks: ""
  },
  {
    code: "301080550",
    section: "M9 ESSENTIALS",
    page: 3,
    signage: "399",
    color: "SAGE",
    position: 8,
    totalPositions: 12,
    slotType: "Folded Tee Stack",
    shelf: "Middle Shelf 8",
    newLine: "NO",
    cutSize: "NO",
    capacity: "",
    remarks: ""
  },
  {
    code: "301078633",
    section: "M9 ESSENTIALS",
    page: 3,
    signage: "399",
    color: "OFF WHITE NEW",
    position: 9,
    totalPositions: 12,
    slotType: "Bottom Stack",
    shelf: "Bottom Shelf 9",
    newLine: "YES",
    cutSize: "NO",
    capacity: "",
    remarks: ""
  },
  {
    code: "301078631",
    section: "M9 ESSENTIALS",
    page: 3,
    signage: "399",
    color: "CHERRY LACQUER",
    position: 10,
    totalPositions: 12,
    slotType: "Bottom Stack",
    shelf: "Bottom Shelf 10",
    newLine: "NO",
    cutSize: "NO",
    capacity: "",
    remarks: ""
  },
  {
    code: "301055218",
    section: "M9 ESSENTIALS",
    page: 3,
    signage: "399",
    color: "DARK NAVY",
    position: 11,
    totalPositions: 12,
    slotType: "Bottom Stack",
    shelf: "Bottom Shelf 11",
    newLine: "NO",
    cutSize: "NO",
    capacity: "",
    remarks: ""
  },
  {
    code: "301078632",
    section: "M9 ESSENTIALS",
    page: 3,
    signage: "399",
    color: "COFFEE",
    position: 12,
    totalPositions: 12,
    slotType: "Bottom Stack",
    shelf: "Bottom Shelf 12",
    newLine: "YES",
    cutSize: "NO",
    capacity: "",
    remarks: ""
  },
  // M9 Cut pieces
  {
    code: "301078630",
    section: "M9 ESSENTIALS",
    page: 3,
    signage: "399",
    color: "BLACK NEW",
    position: 0,
    slotType: "Cut Pieces Tray",
    shelf: "Cut Size Shelf",
    newLine: "NO",
    cutSize: "YES",
    remarks: "CUT PIECES"
  },
  {
    code: "301077491",
    section: "M9 ESSENTIALS",
    page: 3,
    signage: "199",
    color: "ROSIN",
    position: 0,
    slotType: "Cut Pieces Tray",
    shelf: "Cut Size Shelf",
    newLine: "NO",
    cutSize: "YES",
    remarks: "CUT PIECES"
  },

  // --- PAGE 4: M10 ESSENTIALS ---
  {
    code: "301057130",
    section: "M10 ESSENTIALS",
    page: 4,
    signage: "499",
    color: "OFF WHITE",
    position: 1,
    totalPositions: 12,
    slotType: "Shacket Hanger",
    shelf: "Top Row 1",
    newLine: "NO",
    cutSize: "NO",
    remarks: ""
  },
  {
    code: "301075410",
    section: "M10 ESSENTIALS",
    page: 4,
    signage: "999",
    color: "LTGREEN",
    position: 2,
    totalPositions: 12,
    slotType: "Shacket Hanger",
    shelf: "Top Row 2",
    newLine: "NO",
    cutSize: "NO",
    remarks: ""
  },
  {
    code: "301057127",
    section: "M10 ESSENTIALS",
    page: 4,
    signage: "499",
    color: "BROWN",
    position: 3,
    totalPositions: 12,
    slotType: "Shacket Hanger",
    shelf: "Top Row 3",
    newLine: "NO",
    cutSize: "NO",
    remarks: ""
  },
  {
    code: "301075417",
    section: "M10 ESSENTIALS",
    page: 4,
    signage: "999",
    color: "GREY",
    position: 4,
    totalPositions: 12,
    slotType: "Shacket Hanger",
    shelf: "Top Row 4",
    newLine: "NO",
    cutSize: "NO",
    remarks: ""
  },
  {
    code: "301075414",
    section: "M10 ESSENTIALS",
    page: 4,
    signage: "999",
    color: "BLACK",
    position: 5,
    totalPositions: 12,
    slotType: "Middle Shelf Stack",
    shelf: "Middle Row 5",
    newLine: "NO",
    cutSize: "NO",
    remarks: ""
  },
  {
    code: "301057128",
    section: "M10 ESSENTIALS",
    page: 4,
    signage: "499",
    color: "KHAKI",
    position: 6,
    totalPositions: 12,
    slotType: "Middle Shelf Stack",
    shelf: "Middle Row 6",
    newLine: "NO",
    cutSize: "NO",
    remarks: ""
  },

  // --- PAGE 5: MT2-FRONT DENIM WORLD ---
  {
    code: "301081710",
    section: "MT2-FRONT",
    page: 5,
    signage: "799",
    color: "TEAL",
    position: 1,
    totalPositions: 12,
    slotType: "Hanger",
    shelf: "Front Row 1",
    newLine: "NO",
    cutSize: "NO",
    remarks: "DISPLAY 3RD & 4TH SHELF FOR CUT OPTIONS."
  },
  {
    code: "301075846",
    section: "MT2-FRONT",
    page: 5,
    signage: "799",
    color: "DEEP TEAL",
    position: 2,
    totalPositions: 12,
    slotType: "Hanger",
    shelf: "Front Row 2",
    newLine: "NO",
    cutSize: "NO",
    remarks: "DISPLAY 3RD & 4TH SHELF FOR CUT OPTIONS."
  },
  {
    code: "301079243",
    section: "MT2-FRONT",
    page: 5,
    signage: "799",
    color: "OLIVE",
    position: 3,
    totalPositions: 12,
    slotType: "Hanger",
    shelf: "Front Row 3",
    newLine: "YES",
    cutSize: "NO",
    remarks: "DISPLAY 3RD & 4TH SHELF FOR CUT OPTIONS."
  },
  {
    code: "301030889",
    section: "MT2-FRONT",
    page: 5,
    signage: "799",
    color: "OLIVE",
    position: 4,
    totalPositions: 12,
    slotType: "Hanger",
    shelf: "Front Row 4",
    newLine: "NO",
    cutSize: "NO",
    remarks: "DISPLAY 3RD & 4TH SHELF FOR CUT OPTIONS."
  },

  // --- PAGE 6: MT2-BACK DENIM WORLD ---
  {
    code: "301077481",
    section: "MT2-BACK",
    page: 6,
    signage: "399",
    color: "OFF WHITE",
    position: 1,
    totalPositions: 12,
    slotType: "Hanger",
    shelf: "Back Row 1",
    newLine: "YES",
    cutSize: "NO",
    remarks: "DISPLAY 4TH SHELF FOR CUT PIECES."
  },
  {
    code: "301077485",
    section: "MT2-BACK",
    page: 6,
    signage: "399",
    color: "DUSTY PINK",
    position: 2,
    totalPositions: 12,
    slotType: "Hanger",
    shelf: "Back Row 2",
    newLine: "YES",
    cutSize: "NO",
    remarks: "DISPLAY 4TH SHELF FOR CUT PIECES."
  },
  {
    code: "301077484",
    section: "MT2-BACK",
    page: 6,
    signage: "399",
    color: "TEAL",
    position: 3,
    totalPositions: 12,
    slotType: "Hanger",
    shelf: "Back Row 3",
    newLine: "YES",
    cutSize: "NO",
    remarks: "DISPLAY 4TH SHELF FOR CUT PIECES."
  },
  {
    code: "301077483",
    section: "MT2-BACK",
    page: 6,
    signage: "399",
    color: "BLACK",
    position: 4,
    totalPositions: 12,
    slotType: "Hanger",
    shelf: "Back Row 4",
    newLine: "YES",
    cutSize: "NO",
    remarks: "DISPLAY 4TH SHELF FOR CUT PIECES."
  }
];
