/**
 * Preloaded Planogram Cheatsheet Dataset
 * Extracted directly from the Retail Visual Merchandising Cheatsheet Document (All 6 Pages)
 * Total Items: 102 (including all 16 New Lines and 26 Cut Pieces)
 */
window.DEFAULT_PLANOGRAM_DATA = [
  {
    "code": "301081626",
    "section": "M6 DENIM",
    "page": 1,
    "signage": "899",
    "color": "WHITE",
    "position": 1,
    "totalPositions": 14,
    "slotType": "Hanger (Denim)",
    "shelf": "Top Row / Hanger 1",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "14 pcs Per option Denim",
    "remarks": "LAYER 1ST PIECE OF OPTION 1 WITH OPTION 3."
  },
  {
    "code": "301075847",
    "section": "M6 DENIM",
    "page": 1,
    "signage": "899",
    "color": "GREY",
    "position": 2,
    "totalPositions": 14,
    "slotType": "Hanger (Denim)",
    "shelf": "Top Row / Hanger 2",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "14 pcs Per option Denim",
    "remarks": "LAYER 1ST PIECE OF OPTION 1 WITH OPTION 3."
  },
  {
    "code": "301081624",
    "section": "M6 DENIM",
    "page": 1,
    "signage": "899",
    "color": "LT INDIGO",
    "position": 3,
    "totalPositions": 14,
    "slotType": "Hanger (Denim)",
    "shelf": "Top Row / Hanger 3",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "14 pcs Per option Denim",
    "remarks": "LAYER 1ST PIECE OF OPTION 1 WITH OPTION 3."
  },
  {
    "code": "301081625",
    "section": "M6 DENIM",
    "page": 1,
    "signage": "899",
    "color": "TINT",
    "position": 4,
    "totalPositions": 14,
    "slotType": "Hanger (Denim)",
    "shelf": "Top Row / Hanger 4",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "14 pcs Per option Denim",
    "remarks": "LAYER 1ST PIECE OF OPTION 1 WITH OPTION 3."
  },
  {
    "code": "301031222",
    "section": "M6 DENIM",
    "page": 1,
    "signage": "199",
    "color": "WHITE",
    "position": 5,
    "totalPositions": 14,
    "slotType": "Shelf Stack (Tees)",
    "shelf": "Middle Shelf / Stack 5",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "15 pcs Per option Tees",
    "remarks": ""
  },
  {
    "code": "301081994",
    "section": "M6 DENIM",
    "page": 1,
    "signage": "199",
    "color": "BALTIC",
    "position": 6,
    "totalPositions": 14,
    "slotType": "Shelf Stack (Tees)",
    "shelf": "Middle Shelf / Stack 6",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "15 pcs Per option Tees",
    "remarks": ""
  },
  {
    "code": "301078439",
    "section": "M6 DENIM",
    "page": 1,
    "signage": "199",
    "color": "WARM TAUPE",
    "position": 7,
    "totalPositions": 14,
    "slotType": "Shelf Stack (Tees)",
    "shelf": "Middle Shelf / Stack 7",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "15 pcs Per option Tees",
    "remarks": ""
  },
  {
    "code": "301078444",
    "section": "M6 DENIM",
    "page": 1,
    "signage": "199",
    "color": "KHAKI",
    "position": 8,
    "totalPositions": 14,
    "slotType": "Shelf Stack (Tees)",
    "shelf": "Middle Shelf / Stack 8",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "15 pcs Per option Tees",
    "remarks": ""
  },
  {
    "code": "301031226",
    "section": "M6 DENIM",
    "page": 1,
    "signage": "199",
    "color": "BLACK",
    "position": 9,
    "totalPositions": 14,
    "slotType": "Shelf Stack (Tees)",
    "shelf": "Middle Shelf / Stack 9",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "15 pcs Per option Tees",
    "remarks": ""
  },
  {
    "code": "301078443",
    "section": "M6 DENIM",
    "page": 1,
    "signage": "199",
    "color": "CLOUD DANCER",
    "position": 10,
    "totalPositions": 14,
    "slotType": "Shelf Stack (Tees)",
    "shelf": "Middle Shelf / Stack 10",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "15 pcs Per option Tees",
    "remarks": ""
  },
  {
    "code": "301078442",
    "section": "M6 DENIM",
    "page": 1,
    "signage": "199",
    "color": "CAPPUCCINO",
    "position": 11,
    "totalPositions": 14,
    "slotType": "Shelf Stack (Tees)",
    "shelf": "Bottom Shelf / Stack 11",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "15 pcs Per option Tees",
    "remarks": ""
  },
  {
    "code": "301078446",
    "section": "M6 DENIM",
    "page": 1,
    "signage": "199",
    "color": "WINE TASTING",
    "position": 12,
    "totalPositions": 14,
    "slotType": "Shelf Stack (Tees)",
    "shelf": "Bottom Shelf / Stack 12",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "15 pcs Per option Tees",
    "remarks": ""
  },
  {
    "code": "301078441",
    "section": "M6 DENIM",
    "page": 1,
    "signage": "199",
    "color": "TEAL",
    "position": 13,
    "totalPositions": 14,
    "slotType": "Shelf Stack (Tees)",
    "shelf": "Bottom Shelf / Stack 13",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "15 pcs Per option Tees",
    "remarks": ""
  },
  {
    "code": "301078440",
    "section": "M6 DENIM",
    "page": 1,
    "signage": "199",
    "color": "FOREST NIGHT",
    "position": 14,
    "totalPositions": 14,
    "slotType": "Shelf Stack (Tees)",
    "shelf": "Bottom Shelf / Stack 14",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "15 pcs Per option Tees",
    "remarks": ""
  },
  {
    "code": "301081946",
    "section": "M8 DENIM MONO",
    "page": 2,
    "signage": "899",
    "color": "LT INDIGO",
    "position": 23,
    "totalPositions": 14,
    "slotType": "Hanger (Denim)",
    "shelf": "Top Row / Hanger 23",
    "newLine": "YES",
    "cutSize": "NO",
    "capacity": "14 pcs Per option Denim",
    "remarks": ""
  },
  {
    "code": "301081947",
    "section": "M8 DENIM MONO",
    "page": 2,
    "signage": "899",
    "color": "GREY",
    "position": 24,
    "totalPositions": 14,
    "slotType": "Hanger (Denim)",
    "shelf": "Top Row / Hanger 24",
    "newLine": "YES",
    "cutSize": "NO",
    "capacity": "14 pcs Per option Denim",
    "remarks": ""
  },
  {
    "code": "301075849",
    "section": "M8 DENIM MONO",
    "page": 2,
    "signage": "899",
    "color": "MDINDIGO",
    "position": 25,
    "totalPositions": 14,
    "slotType": "Hanger (Denim)",
    "shelf": "Top Row / Hanger 25",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "14 pcs Per option Denim",
    "remarks": ""
  },
  {
    "code": "301081948",
    "section": "M8 DENIM MONO",
    "page": 2,
    "signage": "899",
    "color": "BLACK",
    "position": 26,
    "totalPositions": 14,
    "slotType": "Hanger (Denim)",
    "shelf": "Top Row / Hanger 26",
    "newLine": "YES",
    "cutSize": "NO",
    "capacity": "14 pcs Per option Denim",
    "remarks": ""
  },
  {
    "code": "301079821",
    "section": "M8 DENIM MONO",
    "page": 2,
    "signage": "199",
    "color": "CLOUD DANCER",
    "position": 27,
    "totalPositions": 14,
    "slotType": "Shelf Stack (Tees)",
    "shelf": "Middle Shelf / Stack 27",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "15 pcs Per option Tees",
    "remarks": ""
  },
  {
    "code": "301079822",
    "section": "M8 DENIM MONO",
    "page": 2,
    "signage": "199",
    "color": "COASTAL SHADE",
    "position": 28,
    "totalPositions": 14,
    "slotType": "Shelf Stack (Tees)",
    "shelf": "Middle Shelf / Stack 28",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "15 pcs Per option Tees",
    "remarks": ""
  },
  {
    "code": "301081656",
    "section": "M8 DENIM MONO",
    "page": 2,
    "signage": "199",
    "color": "SHIFTING SAND",
    "position": 29,
    "totalPositions": 14,
    "slotType": "Shelf Stack (Tees)",
    "shelf": "Middle Shelf / Stack 29",
    "newLine": "YES",
    "cutSize": "NO",
    "capacity": "15 pcs Per option Tees",
    "remarks": ""
  },
  {
    "code": "301081658",
    "section": "M8 DENIM MONO",
    "page": 2,
    "signage": "199",
    "color": "APPLE GREEN",
    "position": 30,
    "totalPositions": 14,
    "slotType": "Shelf Stack (Tees)",
    "shelf": "Middle Shelf / Stack 30",
    "newLine": "YES",
    "cutSize": "NO",
    "capacity": "15 pcs Per option Tees",
    "remarks": ""
  },
  {
    "code": "301081654",
    "section": "M8 DENIM MONO",
    "page": 2,
    "signage": "199",
    "color": "BLACK",
    "position": 31,
    "totalPositions": 14,
    "slotType": "Shelf Stack (Tees)",
    "shelf": "Middle Shelf / Stack 31",
    "newLine": "YES",
    "cutSize": "NO",
    "capacity": "15 pcs Per option Tees",
    "remarks": ""
  },
  {
    "code": "301081655",
    "section": "M8 DENIM MONO",
    "page": 2,
    "signage": "199",
    "color": "WHITE",
    "position": 32,
    "totalPositions": 14,
    "slotType": "Bottom Shelf Stack",
    "shelf": "Bottom Shelf / Stack 32",
    "newLine": "YES",
    "cutSize": "NO",
    "capacity": "15 pcs Per option Tees",
    "remarks": ""
  },
  {
    "code": "301079824",
    "section": "M8 DENIM MONO",
    "page": 2,
    "signage": "199",
    "color": "DARK CITRON",
    "position": 33,
    "totalPositions": 14,
    "slotType": "Bottom Shelf Stack",
    "shelf": "Bottom Shelf / Stack 33",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "15 pcs Per option Tees",
    "remarks": ""
  },
  {
    "code": "301079819",
    "section": "M8 DENIM MONO",
    "page": 2,
    "signage": "199",
    "color": "KARANA RED",
    "position": 34,
    "totalPositions": 14,
    "slotType": "Bottom Shelf Stack",
    "shelf": "Bottom Shelf / Stack 34",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "15 pcs Per option Tees",
    "remarks": ""
  },
  {
    "code": "301081657",
    "section": "M8 DENIM MONO",
    "page": 2,
    "signage": "199",
    "color": "BOTTLE GREEN",
    "position": 35,
    "totalPositions": 14,
    "slotType": "Bottom Shelf Stack",
    "shelf": "Bottom Shelf / Stack 35",
    "newLine": "YES",
    "cutSize": "NO",
    "capacity": "15 pcs Per option Tees",
    "remarks": ""
  },
  {
    "code": "301079823",
    "section": "M8 DENIM MONO",
    "page": 2,
    "signage": "199",
    "color": "BLACK",
    "position": 36,
    "totalPositions": 14,
    "slotType": "Bottom Shelf Stack",
    "shelf": "Bottom Shelf / Stack 36",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "15 pcs Per option Tees",
    "remarks": ""
  },
  {
    "code": "301080548",
    "section": "M9 ESSENTIALS",
    "page": 3,
    "signage": "399",
    "color": "GROUND COFFEE",
    "position": 1,
    "totalPositions": 12,
    "slotType": "Shacket Hanger",
    "shelf": "Top Row / Hanger 1",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "Hang 14 pcs Per option",
    "remarks": "LAYER OPTIONS: 1&2, 3&4."
  },
  {
    "code": "301079214",
    "section": "M9 ESSENTIALS",
    "page": 3,
    "signage": "999",
    "color": "WHITE",
    "position": 2,
    "totalPositions": 12,
    "slotType": "Shacket Hanger",
    "shelf": "Top Row / Hanger 2",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "Hang 14 pcs Per option",
    "remarks": "LAYER OPTIONS: 1&2, 3&4."
  },
  {
    "code": "301080551",
    "section": "M9 ESSENTIALS",
    "page": 3,
    "signage": "399",
    "color": "WHITE",
    "position": 3,
    "totalPositions": 12,
    "slotType": "Shacket Hanger",
    "shelf": "Top Row / Hanger 3",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "Hang 14 pcs Per option",
    "remarks": "LAYER OPTIONS: 1&2, 3&4."
  },
  {
    "code": "301079213",
    "section": "M9 ESSENTIALS",
    "page": 3,
    "signage": "999",
    "color": "DARK NAVY",
    "position": 4,
    "totalPositions": 12,
    "slotType": "Shacket Hanger",
    "shelf": "Top Row / Hanger 4",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "Hang 14 pcs Per option",
    "remarks": "LAYER OPTIONS: 1&2, 3&4."
  },
  {
    "code": "301076554",
    "section": "M9 ESSENTIALS",
    "page": 3,
    "signage": "999",
    "color": "OLIVE",
    "position": 5,
    "totalPositions": 12,
    "slotType": "Middle Shelf Stack",
    "shelf": "Middle Shelf / Stack 5",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "Fold 9 pcs Per option",
    "remarks": ""
  },
  {
    "code": "301080549",
    "section": "M9 ESSENTIALS",
    "page": 3,
    "signage": "399",
    "color": "LAVENDER",
    "position": 6,
    "totalPositions": 12,
    "slotType": "Middle Shelf Stack",
    "shelf": "Middle Shelf / Stack 6",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "Fold 9 pcs Per option",
    "remarks": ""
  },
  {
    "code": "301076556",
    "section": "M9 ESSENTIALS",
    "page": 3,
    "signage": "999",
    "color": "BLACK",
    "position": 7,
    "totalPositions": 12,
    "slotType": "Middle Shelf Stack",
    "shelf": "Middle Shelf / Stack 7",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "Fold 9 pcs Per option",
    "remarks": ""
  },
  {
    "code": "301080550",
    "section": "M9 ESSENTIALS",
    "page": 3,
    "signage": "399",
    "color": "SAGE",
    "position": 8,
    "totalPositions": 12,
    "slotType": "Middle Shelf Stack",
    "shelf": "Middle Shelf / Stack 8",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "Fold 9 pcs Per option",
    "remarks": ""
  },
  {
    "code": "301078633",
    "section": "M9 ESSENTIALS",
    "page": 3,
    "signage": "399",
    "color": "OFF WHITE NEW",
    "position": 9,
    "totalPositions": 12,
    "slotType": "Bottom Shelf Stack",
    "shelf": "Bottom Shelf / Stack 9",
    "newLine": "YES",
    "cutSize": "NO",
    "capacity": "Fold 9 pcs Per option",
    "remarks": ""
  },
  {
    "code": "301078631",
    "section": "M9 ESSENTIALS",
    "page": 3,
    "signage": "399",
    "color": "CHERRY LACQUER",
    "position": 10,
    "totalPositions": 12,
    "slotType": "Bottom Shelf Stack",
    "shelf": "Bottom Shelf / Stack 10",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "Fold 9 pcs Per option",
    "remarks": ""
  },
  {
    "code": "301055218",
    "section": "M9 ESSENTIALS",
    "page": 3,
    "signage": "399",
    "color": "DARK NAVY",
    "position": 11,
    "totalPositions": 12,
    "slotType": "Bottom Shelf Stack",
    "shelf": "Bottom Shelf / Stack 11",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "Fold 9 pcs Per option",
    "remarks": ""
  },
  {
    "code": "301078632",
    "section": "M9 ESSENTIALS",
    "page": 3,
    "signage": "399",
    "color": "COFFEE",
    "position": 12,
    "totalPositions": 12,
    "slotType": "Bottom Shelf Stack",
    "shelf": "Bottom Shelf / Stack 12",
    "newLine": "YES",
    "cutSize": "NO",
    "capacity": "Fold 9 pcs Per option",
    "remarks": ""
  },
  {
    "code": "301078630",
    "section": "M9 ESSENTIALS",
    "page": 3,
    "signage": "399",
    "color": "BLACK NEW",
    "position": 13,
    "totalPositions": 24,
    "slotType": "Cut Pieces Tray",
    "shelf": "Bottom Cut Tray 1",
    "newLine": "NO",
    "cutSize": "YES",
    "capacity": "",
    "remarks": "CUT PIECES"
  },
  {
    "code": "301077491",
    "section": "M9 ESSENTIALS",
    "page": 3,
    "signage": "199",
    "color": "ROSIN",
    "position": 14,
    "totalPositions": 24,
    "slotType": "Cut Pieces Tray",
    "shelf": "Bottom Cut Tray 2",
    "newLine": "NO",
    "cutSize": "YES",
    "capacity": "",
    "remarks": "CUT PIECES"
  },
  {
    "code": "301079828",
    "section": "M9 ESSENTIALS",
    "page": 3,
    "signage": "199",
    "color": "OFF WHITE",
    "position": 15,
    "totalPositions": 24,
    "slotType": "Cut Pieces Tray",
    "shelf": "Bottom Cut Tray 3",
    "newLine": "NO",
    "cutSize": "YES",
    "capacity": "",
    "remarks": "CUT PIECES"
  },
  {
    "code": "301079829",
    "section": "M9 ESSENTIALS",
    "page": 3,
    "signage": "199",
    "color": "BLACK",
    "position": 16,
    "totalPositions": 24,
    "slotType": "Cut Pieces Tray",
    "shelf": "Bottom Cut Tray 4",
    "newLine": "NO",
    "cutSize": "YES",
    "capacity": "",
    "remarks": "CUT PIECES"
  },
  {
    "code": "301079826",
    "section": "M9 ESSENTIALS",
    "page": 3,
    "signage": "199",
    "color": "RUST",
    "position": 17,
    "totalPositions": 24,
    "slotType": "Cut Pieces Tray",
    "shelf": "Bottom Cut Tray 5",
    "newLine": "NO",
    "cutSize": "YES",
    "capacity": "",
    "remarks": "CUT PIECES"
  },
  {
    "code": "301079827",
    "section": "M9 ESSENTIALS",
    "page": 3,
    "signage": "199",
    "color": "NAVY",
    "position": 18,
    "totalPositions": 24,
    "slotType": "Cut Pieces Tray",
    "shelf": "Bottom Cut Tray 6",
    "newLine": "NO",
    "cutSize": "YES",
    "capacity": "",
    "remarks": "CUT PIECES"
  },
  {
    "code": "301079825",
    "section": "M9 ESSENTIALS",
    "page": 3,
    "signage": "199",
    "color": "DARK GREEN",
    "position": 19,
    "totalPositions": 24,
    "slotType": "Cut Pieces Tray",
    "shelf": "Bottom Cut Tray 7",
    "newLine": "NO",
    "cutSize": "YES",
    "capacity": "",
    "remarks": "CUT PIECES"
  },
  {
    "code": "301077488",
    "section": "M9 ESSENTIALS",
    "page": 3,
    "signage": "199",
    "color": "CHINO GREEN",
    "position": 20,
    "totalPositions": 24,
    "slotType": "Cut Pieces Tray",
    "shelf": "Bottom Cut Tray 8",
    "newLine": "NO",
    "cutSize": "YES",
    "capacity": "",
    "remarks": "CUT PIECES"
  },
  {
    "code": "301078445",
    "section": "M9 ESSENTIALS",
    "page": 3,
    "signage": "199",
    "color": "ROOIBOS TEA",
    "position": 21,
    "totalPositions": 24,
    "slotType": "Cut Pieces Tray",
    "shelf": "Bottom Cut Tray 9",
    "newLine": "NO",
    "cutSize": "YES",
    "capacity": "",
    "remarks": "CUT PIECES"
  },
  {
    "code": "301077486",
    "section": "M9 ESSENTIALS",
    "page": 3,
    "signage": "199",
    "color": "BURNT ORANGE",
    "position": 22,
    "totalPositions": 24,
    "slotType": "Cut Pieces Tray",
    "shelf": "Bottom Cut Tray 10",
    "newLine": "NO",
    "cutSize": "YES",
    "capacity": "",
    "remarks": "CUT PIECES"
  },
  {
    "code": "301077490",
    "section": "M9 ESSENTIALS",
    "page": 3,
    "signage": "199",
    "color": "ANTARCTICA",
    "position": 23,
    "totalPositions": 24,
    "slotType": "Cut Pieces Tray",
    "shelf": "Bottom Cut Tray 11",
    "newLine": "NO",
    "cutSize": "YES",
    "capacity": "",
    "remarks": "CUT PIECES"
  },
  {
    "code": "301077489",
    "section": "M9 ESSENTIALS",
    "page": 3,
    "signage": "199",
    "color": "BIJOU BLUE",
    "position": 24,
    "totalPositions": 24,
    "slotType": "Cut Pieces Tray",
    "shelf": "Bottom Cut Tray 12",
    "newLine": "NO",
    "cutSize": "YES",
    "capacity": "",
    "remarks": "CUT PIECES"
  },
  {
    "code": "301057130",
    "section": "M10 ESSENTIALS",
    "page": 4,
    "signage": "499",
    "color": "OFF WHITE",
    "position": 1,
    "totalPositions": 12,
    "slotType": "Shacket Hanger",
    "shelf": "Top Row / Hanger 1",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "Hang 14 pcs Per option",
    "remarks": ""
  },
  {
    "code": "301075410",
    "section": "M10 ESSENTIALS",
    "page": 4,
    "signage": "999",
    "color": "LTGREEN",
    "position": 2,
    "totalPositions": 12,
    "slotType": "Shacket Hanger",
    "shelf": "Top Row / Hanger 2",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "Hang 14 pcs Per option",
    "remarks": ""
  },
  {
    "code": "301057127",
    "section": "M10 ESSENTIALS",
    "page": 4,
    "signage": "499",
    "color": "BROWN",
    "position": 3,
    "totalPositions": 12,
    "slotType": "Shacket Hanger",
    "shelf": "Top Row / Hanger 3",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "Hang 14 pcs Per option",
    "remarks": ""
  },
  {
    "code": "301075417",
    "section": "M10 ESSENTIALS",
    "page": 4,
    "signage": "999",
    "color": "GREY",
    "position": 4,
    "totalPositions": 12,
    "slotType": "Shacket Hanger",
    "shelf": "Top Row / Hanger 4",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "Hang 14 pcs Per option",
    "remarks": ""
  },
  {
    "code": "301075414",
    "section": "M10 ESSENTIALS",
    "page": 4,
    "signage": "999",
    "color": "BLACK",
    "position": 5,
    "totalPositions": 12,
    "slotType": "Middle Shelf Stack",
    "shelf": "Middle Row / Stack 5",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "Fold 9 pcs Per option",
    "remarks": ""
  },
  {
    "code": "301057128",
    "section": "M10 ESSENTIALS",
    "page": 4,
    "signage": "499",
    "color": "KHAKI",
    "position": 6,
    "totalPositions": 12,
    "slotType": "Middle Shelf Stack",
    "shelf": "Middle Row / Stack 6",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "Fold 9 pcs Per option",
    "remarks": ""
  },
  {
    "code": "301075416",
    "section": "M10 ESSENTIALS",
    "page": 4,
    "signage": "999",
    "color": "COFFEE",
    "position": 7,
    "totalPositions": 12,
    "slotType": "Middle Shelf Stack",
    "shelf": "Middle Row / Stack 7",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "Fold 9 pcs Per option",
    "remarks": ""
  },
  {
    "code": "301075850",
    "section": "M10 ESSENTIALS",
    "page": 4,
    "signage": "499",
    "color": "BEIGE",
    "position": 8,
    "totalPositions": 12,
    "slotType": "Middle Shelf Stack",
    "shelf": "Middle Row / Stack 8",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "Fold 9 pcs Per option",
    "remarks": ""
  },
  {
    "code": "301077803",
    "section": "M10 ESSENTIALS",
    "page": 4,
    "signage": "499",
    "color": "WHITE",
    "position": 9,
    "totalPositions": 12,
    "slotType": "Bottom Shelf Stack",
    "shelf": "Bottom Row / Stack 9",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "Fold 9 pcs Per option",
    "remarks": ""
  },
  {
    "code": "301077802",
    "section": "M10 ESSENTIALS",
    "page": 4,
    "signage": "499",
    "color": "OLIVE",
    "position": 10,
    "totalPositions": 12,
    "slotType": "Bottom Shelf Stack",
    "shelf": "Bottom Row / Stack 10",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "Fold 9 pcs Per option",
    "remarks": ""
  },
  {
    "code": "301075851",
    "section": "M10 ESSENTIALS",
    "page": 4,
    "signage": "499",
    "color": "COFFEE",
    "position": 11,
    "totalPositions": 12,
    "slotType": "Bottom Shelf Stack",
    "shelf": "Bottom Row / Stack 11",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "Fold 9 pcs Per option",
    "remarks": ""
  },
  {
    "code": "301075844",
    "section": "M10 ESSENTIALS",
    "page": 4,
    "signage": "499",
    "color": "DEEP TEAL",
    "position": 12,
    "totalPositions": 12,
    "slotType": "Bottom Shelf Stack",
    "shelf": "Bottom Row / Stack 12",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "Fold 9 pcs Per option",
    "remarks": ""
  },
  {
    "code": "301081710",
    "section": "MT2-FRONT",
    "page": 5,
    "signage": "799",
    "color": "TEAL",
    "position": 1,
    "totalPositions": 12,
    "slotType": "Center Rail Hanger",
    "shelf": "Front Center Rail 1",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "S 2, M 4, L 4, XL 3, XXL 2 (15 pcs)",
    "remarks": "DISPLAY 3RD & 4TH SHELF FOR CUT OPTIONS."
  },
  {
    "code": "301075846",
    "section": "MT2-FRONT",
    "page": 5,
    "signage": "799",
    "color": "DEEP TEAL",
    "position": 2,
    "totalPositions": 12,
    "slotType": "Center Rail Hanger",
    "shelf": "Front Center Rail 2",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "S 2, M 4, L 4, XL 3, XXL 2 (15 pcs)",
    "remarks": "DISPLAY 3RD & 4TH SHELF FOR CUT OPTIONS."
  },
  {
    "code": "301079243",
    "section": "MT2-FRONT",
    "page": 5,
    "signage": "799",
    "color": "OLIVE",
    "position": 3,
    "totalPositions": 12,
    "slotType": "Center Rail Hanger",
    "shelf": "Front Center Rail 3",
    "newLine": "YES",
    "cutSize": "NO",
    "capacity": "S 2, M 4, L 4, XL 3, XXL 2 (15 pcs)",
    "remarks": "DISPLAY 3RD & 4TH SHELF FOR CUT OPTIONS."
  },
  {
    "code": "301030889",
    "section": "MT2-FRONT",
    "page": 5,
    "signage": "799",
    "color": "OLIVE",
    "position": 4,
    "totalPositions": 12,
    "slotType": "Center Rail Hanger",
    "shelf": "Front Center Rail 4",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "S 2, M 4, L 4, XL 3, XXL 2 (15 pcs)",
    "remarks": "DISPLAY 3RD & 4TH SHELF FOR CUT OPTIONS."
  },
  {
    "code": "301077408",
    "section": "MT2-FRONT",
    "page": 5,
    "signage": "799",
    "color": "BEIGE",
    "position": 5,
    "totalPositions": 12,
    "slotType": "Middle Shelf Stack",
    "shelf": "Middle Shelf / Stack 5",
    "newLine": "YES",
    "cutSize": "NO",
    "capacity": "S 2, M 4, L 4, XL 3, XXL 2 (15 pcs)",
    "remarks": "DISPLAY 3RD & 4TH SHELF FOR CUT OPTIONS."
  },
  {
    "code": "301030888",
    "section": "MT2-FRONT",
    "page": 5,
    "signage": "799",
    "color": "COFFEE",
    "position": 6,
    "totalPositions": 12,
    "slotType": "Middle Shelf Stack",
    "shelf": "Middle Shelf / Stack 6",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "S 2, M 4, L 4, XL 3, XXL 2 (15 pcs)",
    "remarks": "DISPLAY 3RD & 4TH SHELF FOR CUT OPTIONS."
  },
  {
    "code": "301075845",
    "section": "MT2-FRONT",
    "page": 5,
    "signage": "799",
    "color": "BEIGE",
    "position": 7,
    "totalPositions": 12,
    "slotType": "Middle Shelf Stack",
    "shelf": "Middle Shelf / Stack 7",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "S 2, M 4, L 4, XL 3, XXL 2 (15 pcs)",
    "remarks": "DISPLAY 3RD & 4TH SHELF FOR CUT OPTIONS."
  },
  {
    "code": "301057123",
    "section": "MT2-FRONT",
    "page": 5,
    "signage": "799",
    "color": "DUSTY PINK",
    "position": 8,
    "totalPositions": 12,
    "slotType": "Middle Shelf Stack",
    "shelf": "Middle Shelf / Stack 8",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "S 2, M 4, L 4, XL 3, XXL 2 (15 pcs)",
    "remarks": "DISPLAY 3RD & 4TH SHELF FOR CUT OPTIONS."
  },
  {
    "code": "301030887",
    "section": "MT2-FRONT",
    "page": 5,
    "signage": "799",
    "color": "CHALK",
    "position": 9,
    "totalPositions": 12,
    "slotType": "Bottom Shelf Stack",
    "shelf": "Bottom Shelf / Stack 9",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "S 2, M 4, L 4, XL 3, XXL 2 (15 pcs)",
    "remarks": "DISPLAY 3RD & 4TH SHELF FOR CUT OPTIONS."
  },
  {
    "code": "301057124",
    "section": "MT2-FRONT",
    "page": 5,
    "signage": "799",
    "color": "MD BLUE",
    "position": 10,
    "totalPositions": 12,
    "slotType": "Bottom Shelf Stack",
    "shelf": "Bottom Shelf / Stack 10",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "S 2, M 4, L 4, XL 3, XXL 2 (15 pcs)",
    "remarks": "DISPLAY 3RD & 4TH SHELF FOR CUT OPTIONS."
  },
  {
    "code": "301057126",
    "section": "MT2-FRONT",
    "page": 5,
    "signage": "799",
    "color": "WHITE",
    "position": 11,
    "totalPositions": 12,
    "slotType": "Bottom Shelf Stack",
    "shelf": "Bottom Shelf / Stack 11",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "S 2, M 4, L 4, XL 3, XXL 2 (15 pcs)",
    "remarks": "DISPLAY 3RD & 4TH SHELF FOR CUT OPTIONS."
  },
  {
    "code": "301055217",
    "section": "MT2-FRONT",
    "page": 5,
    "signage": "799",
    "color": "NAVY",
    "position": 12,
    "totalPositions": 12,
    "slotType": "Bottom Shelf Stack",
    "shelf": "Bottom Shelf / Stack 12",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "S 2, M 4, L 4, XL 3, XXL 2 (15 pcs)",
    "remarks": "DISPLAY 3RD & 4TH SHELF FOR CUT OPTIONS."
  },
  {
    "code": "301073490",
    "section": "MT2-FRONT",
    "page": 5,
    "signage": "799",
    "color": "GREEN",
    "position": 13,
    "totalPositions": 15,
    "slotType": "Cut Pieces Tray",
    "shelf": "3rd/4th Shelf Cut Option 1",
    "newLine": "NO",
    "cutSize": "YES",
    "capacity": "",
    "remarks": "DISPLAY 3RD & 4TH SHELF FOR CUT OPTIONS."
  },
  {
    "code": "301073491",
    "section": "MT2-FRONT",
    "page": 5,
    "signage": "799",
    "color": "OFF WHITE",
    "position": 14,
    "totalPositions": 15,
    "slotType": "Cut Pieces Tray",
    "shelf": "3rd/4th Shelf Cut Option 2",
    "newLine": "NO",
    "cutSize": "YES",
    "capacity": "",
    "remarks": "DISPLAY 3RD & 4TH SHELF FOR CUT OPTIONS."
  },
  {
    "code": "301073489",
    "section": "MT2-FRONT",
    "page": 5,
    "signage": "799",
    "color": "BLUE",
    "position": 15,
    "totalPositions": 15,
    "slotType": "Cut Pieces Tray",
    "shelf": "3rd/4th Shelf Cut Option 3",
    "newLine": "NO",
    "cutSize": "YES",
    "capacity": "",
    "remarks": "DISPLAY 3RD & 4TH SHELF FOR CUT OPTIONS."
  },
  {
    "code": "301077481",
    "section": "MT2-BACK",
    "page": 6,
    "signage": "399",
    "color": "OFF WHITE",
    "position": 1,
    "totalPositions": 12,
    "slotType": "Center Rail Hanger",
    "shelf": "Back Center Rail 1",
    "newLine": "YES",
    "cutSize": "NO",
    "capacity": "S 2, M 4, L 4, XL 3, XXL 2 (15 pcs)",
    "remarks": "DISPLAY 4TH SHELF FOR CUT PIECES."
  },
  {
    "code": "301077485",
    "section": "MT2-BACK",
    "page": 6,
    "signage": "399",
    "color": "DUSTY PINK",
    "position": 2,
    "totalPositions": 12,
    "slotType": "Center Rail Hanger",
    "shelf": "Back Center Rail 2",
    "newLine": "YES",
    "cutSize": "NO",
    "capacity": "S 2, M 4, L 4, XL 3, XXL 2 (15 pcs)",
    "remarks": "DISPLAY 4TH SHELF FOR CUT PIECES."
  },
  {
    "code": "301077484",
    "section": "MT2-BACK",
    "page": 6,
    "signage": "399",
    "color": "TEAL",
    "position": 3,
    "totalPositions": 12,
    "slotType": "Center Rail Hanger",
    "shelf": "Back Center Rail 3",
    "newLine": "YES",
    "cutSize": "NO",
    "capacity": "S 2, M 4, L 4, XL 3, XXL 2 (15 pcs)",
    "remarks": "DISPLAY 4TH SHELF FOR CUT PIECES."
  },
  {
    "code": "301077483",
    "section": "MT2-BACK",
    "page": 6,
    "signage": "399",
    "color": "BLACK",
    "position": 4,
    "totalPositions": 12,
    "slotType": "Center Rail Hanger",
    "shelf": "Back Center Rail 4",
    "newLine": "YES",
    "cutSize": "NO",
    "capacity": "S 2, M 4, L 4, XL 3, XXL 2 (15 pcs)",
    "remarks": "DISPLAY 4TH SHELF FOR CUT PIECES."
  },
  {
    "code": "301073887",
    "section": "MT2-BACK",
    "page": 6,
    "signage": "399",
    "color": "WHITE",
    "position": 5,
    "totalPositions": 12,
    "slotType": "Middle Shelf Stack",
    "shelf": "Middle Shelf / Stack 5",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "S 2, M 4, L 4, XL 3, XXL 2 (15 pcs)",
    "remarks": "DISPLAY 4TH SHELF FOR CUT PIECES."
  },
  {
    "code": "301073891",
    "section": "MT2-BACK",
    "page": 6,
    "signage": "399",
    "color": "RUST",
    "position": 6,
    "totalPositions": 12,
    "slotType": "Middle Shelf Stack",
    "shelf": "Middle Shelf / Stack 6",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "S 2, M 4, L 4, XL 3, XXL 2 (15 pcs)",
    "remarks": "DISPLAY 4TH SHELF FOR CUT PIECES."
  },
  {
    "code": "301073888",
    "section": "MT2-BACK",
    "page": 6,
    "signage": "399",
    "color": "BLUE",
    "position": 7,
    "totalPositions": 12,
    "slotType": "Middle Shelf Stack",
    "shelf": "Middle Shelf / Stack 7",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "S 2, M 4, L 4, XL 3, XXL 2 (15 pcs)",
    "remarks": "DISPLAY 4TH SHELF FOR CUT PIECES."
  },
  {
    "code": "301073890",
    "section": "MT2-BACK",
    "page": 6,
    "signage": "399",
    "color": "BLACK",
    "position": 8,
    "totalPositions": 12,
    "slotType": "Middle Shelf Stack",
    "shelf": "Middle Shelf / Stack 8",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "S 2, M 4, L 4, XL 3, XXL 2 (15 pcs)",
    "remarks": "DISPLAY 4TH SHELF FOR CUT PIECES."
  },
  {
    "code": "301061227",
    "section": "MT2-BACK",
    "page": 6,
    "signage": "399",
    "color": "OFF WHITE",
    "position": 9,
    "totalPositions": 12,
    "slotType": "Lower Shelf Stack",
    "shelf": "Lower Shelf / Stack 9",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "S 2, M 4, L 4, XL 3, XXL 2 (15 pcs)",
    "remarks": "DISPLAY 4TH SHELF FOR CUT PIECES."
  },
  {
    "code": "301061228",
    "section": "MT2-BACK",
    "page": 6,
    "signage": "399",
    "color": "SUMMER SAND",
    "position": 10,
    "totalPositions": 12,
    "slotType": "Lower Shelf Stack",
    "shelf": "Lower Shelf / Stack 10",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "S 2, M 4, L 4, XL 3, XXL 2 (15 pcs)",
    "remarks": "DISPLAY 4TH SHELF FOR CUT PIECES."
  },
  {
    "code": "301081498",
    "section": "MT2-BACK",
    "page": 6,
    "signage": "399",
    "color": "GREEN",
    "position": 11,
    "totalPositions": 12,
    "slotType": "Lower Shelf Stack",
    "shelf": "Lower Shelf / Stack 11",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "S 2, M 4, L 4, XL 3, XXL 2 (15 pcs)",
    "remarks": "DISPLAY 4TH SHELF FOR CUT PIECES."
  },
  {
    "code": "301061225",
    "section": "MT2-BACK",
    "page": 6,
    "signage": "399",
    "color": "BLACK",
    "position": 12,
    "totalPositions": 12,
    "slotType": "Lower Shelf Stack",
    "shelf": "Lower Shelf / Stack 12",
    "newLine": "NO",
    "cutSize": "NO",
    "capacity": "S 2, M 4, L 4, XL 3, XXL 2 (15 pcs)",
    "remarks": "DISPLAY 4TH SHELF FOR CUT PIECES."
  },
  {
    "code": "301056751",
    "section": "MT2-BACK",
    "page": 6,
    "signage": "399",
    "color": "BRIGHT WHITE",
    "position": 13,
    "totalPositions": 23,
    "slotType": "Cut Pieces Tray",
    "shelf": "4th Shelf Cut Option 1",
    "newLine": "NO",
    "cutSize": "YES",
    "capacity": "",
    "remarks": "DISPLAY 4TH SHELF FOR CUT PIECES."
  },
  {
    "code": "301056756",
    "section": "MT2-BACK",
    "page": 6,
    "signage": "399",
    "color": "FUTURE GREY",
    "position": 14,
    "totalPositions": 23,
    "slotType": "Cut Pieces Tray",
    "shelf": "4th Shelf Cut Option 2",
    "newLine": "NO",
    "cutSize": "YES",
    "capacity": "",
    "remarks": "DISPLAY 4TH SHELF FOR CUT PIECES."
  },
  {
    "code": "301056752",
    "section": "MT2-BACK",
    "page": 6,
    "signage": "399",
    "color": "ELEMENTAL BLUE",
    "position": 15,
    "totalPositions": 23,
    "slotType": "Cut Pieces Tray",
    "shelf": "4th Shelf Cut Option 3",
    "newLine": "NO",
    "cutSize": "YES",
    "capacity": "",
    "remarks": "DISPLAY 4TH SHELF FOR CUT PIECES."
  },
  {
    "code": "301056753",
    "section": "MT2-BACK",
    "page": 6,
    "signage": "399",
    "color": "GROUND COFFEE",
    "position": 16,
    "totalPositions": 23,
    "slotType": "Cut Pieces Tray",
    "shelf": "4th Shelf Cut Option 4",
    "newLine": "NO",
    "cutSize": "YES",
    "capacity": "",
    "remarks": "DISPLAY 4TH SHELF FOR CUT PIECES."
  },
  {
    "code": "301056754",
    "section": "MT2-BACK",
    "page": 6,
    "signage": "399",
    "color": "LAVENDERE",
    "position": 17,
    "totalPositions": 23,
    "slotType": "Cut Pieces Tray",
    "shelf": "4th Shelf Cut Option 5",
    "newLine": "NO",
    "cutSize": "YES",
    "capacity": "",
    "remarks": "DISPLAY 4TH SHELF FOR CUT PIECES."
  },
  {
    "code": "301056755",
    "section": "MT2-BACK",
    "page": 6,
    "signage": "399",
    "color": "SAGE",
    "position": 18,
    "totalPositions": 23,
    "slotType": "Cut Pieces Tray",
    "shelf": "4th Shelf Cut Option 6",
    "newLine": "NO",
    "cutSize": "YES",
    "capacity": "",
    "remarks": "DISPLAY 4TH SHELF FOR CUT PIECES."
  },
  {
    "code": "301077815",
    "section": "MT2-BACK",
    "page": 6,
    "signage": "399",
    "color": "BITTER CHOCOLATE",
    "position": 19,
    "totalPositions": 23,
    "slotType": "Cut Pieces Tray",
    "shelf": "4th Shelf Cut Option 7",
    "newLine": "NO",
    "cutSize": "YES",
    "capacity": "",
    "remarks": "DISPLAY 4TH SHELF FOR CUT PIECES."
  },
  {
    "code": "301077816",
    "section": "MT2-BACK",
    "page": 6,
    "signage": "399",
    "color": "WHITE",
    "position": 20,
    "totalPositions": 23,
    "slotType": "Cut Pieces Tray",
    "shelf": "4th Shelf Cut Option 8",
    "newLine": "NO",
    "cutSize": "YES",
    "capacity": "",
    "remarks": "DISPLAY 4TH SHELF FOR CUT PIECES."
  },
  {
    "code": "301077817",
    "section": "MT2-BACK",
    "page": 6,
    "signage": "399",
    "color": "LICHEN BLUE",
    "position": 21,
    "totalPositions": 23,
    "slotType": "Cut Pieces Tray",
    "shelf": "4th Shelf Cut Option 9",
    "newLine": "NO",
    "cutSize": "YES",
    "capacity": "",
    "remarks": "DISPLAY 4TH SHELF FOR CUT PIECES."
  },
  {
    "code": "301061226",
    "section": "MT2-BACK",
    "page": 6,
    "signage": "399",
    "color": "MINT",
    "position": 22,
    "totalPositions": 23,
    "slotType": "Cut Pieces Tray",
    "shelf": "4th Shelf Cut Option 10",
    "newLine": "NO",
    "cutSize": "YES",
    "capacity": "",
    "remarks": "DISPLAY 4TH SHELF FOR CUT PIECES."
  },
  {
    "code": "301078464",
    "section": "MT2-BACK",
    "page": 6,
    "signage": "399",
    "color": "HONEY MUSTARD",
    "position": 23,
    "totalPositions": 23,
    "slotType": "Cut Pieces Tray",
    "shelf": "4th Shelf Cut Option 11",
    "newLine": "NO",
    "cutSize": "YES",
    "capacity": "",
    "remarks": "DISPLAY 4TH SHELF FOR CUT PIECES."
  }
];
